

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz_demo_db?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    #initialization-mode: ALWAYS
  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
#        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        dialect: org.hibernate.dialect.MySQL8Dialect
  # Hibernate ddl auto (create, create-drop, validate, update)
    #hibernate:
      #ddl-auto: 'create-drop'
      #ddl-auto: update
    open-in-view: false
    show-sql: true

  ## QuartzProperties
  quartz:
    # this property should be different for different clusters. other case it provides conflicts because of job types
    scheduler-name: 'quartz-spam'
    ## correct name is 'quartz-mix'
    #scheduler-name: 'quartz-mix'
    job-store-type: jdbc
    jdbc:
#      schema: classpath:org/quartz/impl/jdbcjobstore/tables_mysql_innodb.sql
#      schema: classpath:org/quartz/impl/jdbcjobstore/tables_mysql.sql
      schema: classpath:db/tables_mysql_innodb.sql
      ## next property can be used for schema initialization for first time
      #initialize-schema: ALWAYS
      # the property is used in case DB is initialized
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          threadPool:
            threadCount: 5

  ## MailProperties
  mail:
    host: smtp.gmail.com
    port: 587
    username: rajeevc217@gmail.com
    password:

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      example:
        quartz: TRACE
    org:
      hibernate: DEBUG
      springframework: INFO

